#!/bin/sh

while [ 1 ]
do
    case "$1" in
        "")     
            echo I need a file of extensions to delete....
            exit 1
            ;;
        "-d")
            cd "$1" > /dev/null 2>&1
            [ "$?" = "1" ] || echo "Invalid directory: exiting..."; exit
            ;;
    esac
    shift
done

extensions_to_delete=()

count=0
while read file
do

    echo extensions_to_delete[$count]=$file
    count=$[ count + 1 ]
done < $1

for file in $(ls *)
do
    if [ -f file ]
    then
        echo $file
    fi
done

read -p "Do you want to erase the above files?" answer

