#!/bin/sh

brave 'https://taosschools.instructure.com/courses/11726/assignments/126049' 'https://taosschools.instructure.com/courses/12374/assignments/121414' 'https://taosschools.instructure.com/courses/12374/assignments/121658?module_item_id=219380' 'file:///Users/ladmin/Downloads/Reading%20Handout-%20Domesticating%20Animals.pdf' 'https://taosschools.instructure.com/courses/12998/assignments/126042?module_item_id=223702'
